# Generated by Django 5.1.7 on 2025-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knife', '0003_alter_care_image_alter_repair_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='knife',
            name='post_office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
