# Generated by Django 5.1.7 on 2025-04-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knife', '0005_care_post_office_repair_post_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='image',
            field=models.ImageField(blank=True, upload_to='knives/'),
        ),
    ]
