# Generated by Django 5.1.7 on 2025-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knife', '0006_alter_knife_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knife',
            name='types',
        ),
        migrations.AlterField(
            model_name='care',
            name='image',
            field=models.ImageField(default='path/to/default_image', upload_to='knives/'),
        ),
        migrations.AlterField(
            model_name='care',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='knife',
            name='image',
            field=models.ImageField(default='path/to/default_image', upload_to='knives/'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='image',
            field=models.ImageField(default='path/to/default_image', upload_to='knives/'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
