# Generated by Django 5.1.7 on 2025-04-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knife', '0007_remove_knife_types_alter_care_image_alter_care_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knife',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
