# Generated by Django 5.1.7 on 2025-04-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knife', '0009_category_remove_knife_type_knife_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knives', to='knife.category'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='mechanism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanisms', to='knife.category'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_office', to='knife.category'),
        ),
    ]
