# Generated by Django 5.1.7 on 2025-04-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knife', '0010_alter_knife_category_alter_knife_mechanism_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knife',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knife.category'),
        ),
        migrations.AlterField(
            model_name='knife',
            name='mechanism',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='knife',
            name='post_office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
